load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "functions_test",
    srcs = [
        "functions_test.cpp",
    ],
    deps = [
        "//:functions",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "deheap_test",
    srcs = [
        "deheap_test.cpp",
    ],
    deps = [
        "//:deheap",
        "@com_google_googletest//:gtest_main",
    ],
)
